############################
## CHANGE THESE
############################

baseURL: 'https://volteret4.github.io/volteretaportabaco'
title: volteretaportabaco

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


